# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab7017cab486ac74f8cfdf20d9f936c398ab00a9097966f2b61dcbc5b016312b1593102bc111fee6b0014d58919fd3fa9848c2dc9d6a96f37ec3116dba6148d4

test:
  secret_key_base: babb03de4645682bd41cdd315923adedf8bd4b3b6b19bb34359bf53ed066911479ceef851b997c099d9d287b3fc88d2133e95659df25ef7d048b9538c84669c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
